apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: backend 
data:
  mongodb.conf: |

    net:
      bindIp: 0.0.0.0
      port: 27017

    storage:
      dbPath: /data/db
      journal:
        enabled: true

 
    replication:
      replSetName: rs0

  
    security:
      authorization: "disabled"

   
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
      verbosity: 0
