apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: sonarqube
type: Opaque
data:
  POSTGRES_DB: c29uYXJxdWJl
  POSTGRES_USER:  c29uYXI=
  POSTGRES_PASSWORD:  empjeHg1NTUhZGRTSg==
 