apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: testing
type: Opaque
data:
  POSTGRES_DB: <base64-encoded-db-name>
  POSTGRES_USER: <base64-encoded-db-username>
  POSTGRES_PASSWORD: <base64-encoded-db-password>
