apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: testing
spec:
  selector:
    app: sonarqube-postgres
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
