apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: sonarqube
spec:
  type: NodePort  
  selector:
    app: sonar-postgres  
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32500  # NodePort range is typically 30000-32767
