apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: testing
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 32000  # You can choose a specific port within the NodePort range (30000-32767)
  selector:
    app: eventhandler
