apiVersion: v1
kind: Service
metadata:
  name: eventhandler-service
  namespace: testing
spec:
  selector:
    app: eventhandler
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000  # You can choose a port between 30000-32767
