apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: testing  
spec:
  type: NodePort
  ports:
  - port: 5601        # The port Kibana listens on inside the cluster
    targetPort: 5601  # The port exposed by the Kibana container
    nodePort: 32001   # The port that will be exposed on the Minikube node
  selector:
    app:  eventhandler
