apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Make sure this matches your StorageClass
