apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-test
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        image: rabebhamd/frontend-service:test 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
