apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - backend-configmap-test.yaml  
 - backend-secrets-test.yaml 
 - backend-deployment-test.yaml 
 - backend-service-test.yaml 
 - image-pull-secret-test.yaml 