apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: testing
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8082 # Port exposed by the Service
      targetPort: 3000  # Port inside the container
      nodePort: 30080  