apiVersion: v1
kind: Secret
metadata:
  name: contracts-secrets
type: Opaque
data:
  WALLET_SECRET_KEY: UzEyUzhicnpVZUsxUXdvUmJHUGtYdjRBU1RWSEFXQzZKVWJ0ZU5ZQzVKSGFrZmRvclFwUgo=
  JSON_RPC_URL_PUBLIC: aHR0cHM6Ly9idWlsZG5ldC5tYXNzYS5uZXQvYXBpL3YyOjMzMDM1Cg==
