apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: contracts-kustomization  # Specify a unique name for the Kustomization
  namespace: flux-system  # Specify the namespace where this Kustomization applies
spec:
  interval: 10m  # Sync interval for Flux
  path: "./testing/contracts"  
  prune: true 
  sourceRef:
    kind: GitRepository
    name:  K8s-testing
    namespace: flux-system
  targetNamespace: testing 

