apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backend-kustomization-prod
  namespace: flux-system
spec:
  interval: 1m
  path: "./prod/backend"
  prune: true
  force: true 
  sourceRef:
    kind: GitRepository
    name: k8s-testing-repo 
    namespace: flux-system
  images:
    - name: rabebhamd/backend-service
      newName: rabebhamd/backend-service
      newTag: prod
  targetNamespace: production
