apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: contracts-kustomization-prod
  namespace: flux-system
spec:
  interval: 1m
  path: "./prod/contracts"
  prune: true
  force: true 
  sourceRef:
    kind: GitRepository
    name: k8s-testing-repo 
    namespace: flux-system
  images:
    - name: rabebhamd/whitelist-contracts
      newName: rabebhamd/whitelist-contracts
      newTag:  prod
    
    - name: rabebhamd/contratcs
      newName: rabebhamd/contratcs
      newTag: prod
  targetNamespace: production
