apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frontend-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: "./prod/Frontend"
  prune: true
  force: true 
  sourceRef:
    kind: GitRepository
    name: k8s-testing-repo 
    namespace: flux-system
  images:
    - name: rabebhamd/frontend-service
      newName: rabebhamd/frontend-service
      newTag: prod # Specify the tag you want to monitor
  targetNamespace: production
