apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi  # Match the PVC size
  accessModes:
    - ReadWriteOnce  # Match the PVC access mode
  storageClassName: local-storage  # Use the StorageClass you created
  hostPath:
    path: "/mnt/data/elasticsearch"  # Local path on the node where data will be stored
