apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: eventhandler
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  # Reference the StorageClass
  resources:
    requests:
      storage: 2Gi  # Requesting 10Gi of storage
