apiVersion: v1
kind: Service
metadata:
  name: eventhandler-service
  namespace: production
spec:
  type: NodePort  # Change the type to NodePort
  selector:
    app: eventhandler
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000  # NodePort should be in the range 30000-32767
