apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: eventhandler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage 
