apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL2FkbWluOjE0N3phYWhAbW9uZ28tc2VydmljZS10ZXN0OjI3MDE3L215ZGF0YWJhc2U/YXV0aFNvdXJjZT1hZG1pbg==
