apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-test
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rabebhamd/backend-service:test3
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets-test
              key: mongo-uri
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      imagePullSecrets:
      - name: regcred
