apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap-test
  namespace: testing
data:
  MONGO_URI: 'mongodb://admin:147zaah@mongo-service-test:27017/mydatabase?authSource=admin'
  LOG_LEVEL: "info"
 