apiVersion: v1
kind: Service
metadata:
  name: backend-service-test
  namespace: testing
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081  # Port exposed by the Service
      targetPort: 3000  # Port inside the container
