apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-test
  namespace: production
spec:
  replicas: 2  # Ensure two replicas
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker
                operator: In
                values:
                - worker1
                - worker2  # Ensure backend pods are scheduled on worker1 and worker2
      containers:
      - name: backend
        image: rabebhamd/backend-service:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: mongo-uri
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      imagePullSecrets:
      - name: regcred
