apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap-test
  namespace: production
data:
  MONGO_URI: 'mongodb://admin:147zaah@mongo-service.mongodb.svc.cluster.local:27017/mydatabase?authSource=admin'
  LOG_LEVEL: "info"
 