apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
  labels:
    app: backend
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      env: production
  template:
    metadata:
      labels:
        app: backend
        env: production
    spec:
      containers:
      - name: backend
        image: my-backend:prod
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-prod:27017/backend
