apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - backend-configmap.yaml  
 - backend-secrets.yaml 
 - backend-deployment.yaml 
 - backend-service.yaml 
 - image-pull-secret.yaml 