apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: NodePort  # Use LoadBalancer if using a cloud provider
  ports:
  - port: 3200
    targetPort: 3200
    nodePort: 32004  # Adjust this as needed
  selector:
    app: grafana
