apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: backend-image-automation
  namespace: flux-system
spec:
  interval: 1m  # Frequency to check for image updates
  sourceRef:
    kind: GitRepository
    name: k8s-testing-repo  # Reference to your Git repository
  git:
    checkout:
      ref:
        branch: main  # Branch to monitor for changes
    commit:
      author:
        email: "rabeb.hamed@supcom.tn"
        name: "flux-bot"
    push:
      branch: main  # Branch to push changes to
  update:
    strategy: Setters  # Strategy for updating the manifests
