apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: your-kustomization-name
  namespace: flux-system
spec:
  interval: 10m # Frequency at which Flux will reconcile the manifests
  path: "./testing/kustomization.yaml" # Path to the kustomization directory relative to the source
  prune: true
  sourceRef:
    kind: GitRepository
    name: K8s-testing
    namespace: flux-system
  targetNamespace: testing # Namespace where the resources will be deployed
