apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-prod
  labels:
    app: mongodb
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
      env: production
  template:
    metadata:
      labels:
        app: mongodb
        env: production
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-prod
