apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: mongodb
spec:
  replicas: 2  # Ensure two replicas, one on each node
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker
                operator: In
                values:
                - worker1
                - worker2  # Ensure MongoDB pods are scheduled on worker1 and worker2 only
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mongodb
            topologyKey: "kubernetes.io/hostname"  # Spread pods across different nodes
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-config
          mountPath: /etc/mongo
          subPath: mongodb.conf
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-log
          mountPath: /var/log/mongodb
      volumes:
      - name: mongo-config
        configMap:
          name: mongo-configmap-test
          items:
          - key: mongodb.conf
            path: mongodb.conf
      - name: mongo-data
        emptyDir: {}
      - name: mongo-log
        emptyDir: {}

      restartPolicy: Always
