apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongodb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  # Ensure this matches the PVC
  hostPath:
    path: "/mnt/data/mongodb"  # Adjust the local storage path as needed



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: local-storage 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
