name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Verify kubectl version
      run: kubectl version --client

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./prod/backend/backend-configmap.yaml --namespace production
        kubectl apply -f ./prod/backend/backend-deployment.yaml --namespace production
        kubectl apply -f ./prod/backend/backend-secrets.yaml --namespace production
        kubectl apply -f ./prod/backend/backend-service.yaml --namespace production
