# .github/workflows/cd-frontend.yml
name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - './prod/Frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: kubectl apply -f /prod/Frontend/ --namespace production
