# .github/workflows/cd-frontend.yml
name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Verify kubectl version
      run: kubectl version --client

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./prod/Frontend/frontend-deployment.yaml --namespace production
        kubectl apply -f ./prod/Frontend/frontend-service.yaml --namespace production





